# Generated by Django 5.1.3 on 2024-11-18 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pages", "0002_delete_car"),
    ]

    operations = [
        migrations.CreateModel(
            name="Female",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_female", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Male",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("male_name", models.CharField(max_length=50)),
                (
                    "girls",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.female"
                    ),
                ),
            ],
        ),
    ]
