# Generated by Django 5.1.3 on 2024-11-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_product_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="User_name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("watch", models.ManyToManyField(null=True, to="pages.video")),
            ],
        ),
    ]
