# Generated by Django 5.1.3 on 2024-11-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_video_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_name",
            name="watch",
            field=models.ManyToManyField(to="pages.video"),
        ),
    ]
