# Generated by Django 5.1.3 on 2024-11-20 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_test_date_time_test_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="date_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
